# Generated by Django 4.2.18 on 2025-07-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_rename_todo_task_rename_task_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
