# Generated by Django 4.2.18 on 2025-07-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_remove_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='createed_at',
            new_name='created_at',
        ),
    ]
