# Generated by Django 4.2.18 on 2025-07-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_rename_createed_at_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
