# Generated by Django 4.2.18 on 2025-07-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_remove_task_completed_remove_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
